# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rbhome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackyardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=6)),
                ('size', models.IntegerField(default=0)),
                ('rent', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rbhome.Userprofile')),
            ],
        ),
    ]
