# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 14:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rbhome', '0002_backyardmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image_url',
            new_name='image_url1',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_url2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_url3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_url4',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_url5',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='backyardmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
