# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rbhome', '0003_auto_20160709_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image_url1',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image_url2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image_url3',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image_url4',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image_url5',
        ),
        migrations.AddField(
            model_name='backyardmodel',
            name='image_url1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='backyardmodel',
            name='image_url2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='backyardmodel',
            name='image_url3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='backyardmodel',
            name='image_url4',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='backyardmodel',
            name='image_url5',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
